package p000;

/* compiled from: jv */
public class R$id {
    public static String $assertionsDisabled = "Loading...";
    public static String f241A = "Forgotten password?";
    public static String ANDROID_VERSION = " from your ignore list first";
    public static String f242B = "Try again";
    public static String FALSE = "Select";
    public static String f243H = "Forgotten your password? <col=ffffff>Click here.";
    public static String ID = "This is a <col=00ffff>Beta<col=ffffff> world.";
    public static String INTEGER = "K";
    public static String LOG = "Loaded config";
    public static String LOG_TAG = "Click to switch";
    public static String f244M = "Login";
    public static String Name = "as it was used to break our rules.";
    public static String PHONE_MODEL = "Please remove ";
    public static String TAG = "M";
    public static String TITLE = "Your normal account will not be affected.";
    public static String TRUE = "Continue";
    public static String Title = "Loaded sprites";
    public static String UNKNOWN = "wave2:";
    public static String ZERO = "This is a <col=ffff00>High Risk<col=ffffff> world.";
    public static String _lock = "Discard";
    public static String f245a = "Existing User";
    public static String accountName = "";
    public static String accountUuid = "Login server offline.";
    public static String action = "Please try again.";
    public static String actions = "For accounts created after 24th November 2010, please use your";
    public static String address = "Please wait a few minutes before trying again.";
    public static String app = "";
    public static String appName = " is already on your friend list";
    public static String artist = "glow1:";
    public static String author = "yellow:";
    public static String f246b = "Error loading your profile.";
    public static String base = "Please contact customer support.";
    public static String begin = "";
    public static String body = "Enter the 6-digit code generated by your";
    public static String buf = "Use";
    public static String buffer = " has logged in.";
    public static String f247c = "Please wait 1 minute and try again.";
    public static String cache = "This world is running a closed Beta.";
    public static String category = "You need to vote to play!";
    public static String channel = "Select a world";
    public static String charset = "skill-";
    public static String client = "not work on this world.";
    public static String code = "No response from server.";
    public static String color = "glow3:";
    public static String colors = "Please verify your account status by";
    public static String command = "glow1:";
    public static String comment = "Please reload this page.";
    public static String comments = "We suspect someone knows your password.";
    public static String config = "Your account has been disabled.";
    public static String configuration = "Hide username";
    public static String connection = "Loaded world map";
    public static String content = "green:";
    public static String contentType = "Loading world map - ";
    public static String context = "The part of the website you are trying";
    public static String count = "Please wait...";
    public static String counter = "Members object";
    public static String created = "";
    public static String current = "";
    public static String f248d = "";
    public static String data = "";
    public static String date = "red:";
    public static String dateFormat = "Sorry, but your account is not eligible to play.";
    public static String day = "Your profile will be transferred in:";
    public static String db = "session or the server is too busy right now.";
    public static String debug = "You are standing in a members-only area.";
    public static String desc = "Loading wordpack - ";
    public static String description = "red:";
    public static String destination = "Unable to connect.";
    public static String device = "Error connecting to server.";
    public static String digest = "Enter your username/email & password.";
    public static String dir = "";
    public static String direction = "Your account is currently inaccessible.";
    public static String directory = "2010, this will be the creation email address.";
    public static String duration = "this out by visiting the billing system.";
    public static String f249e = "";
    public static String edit = "Players can attack each other almost everywhere";
    public static String element = "Malformed login packet.";
    public static String email = "Please remove ";
    public static String enabled = "Please try using a different world.";
    public static String encoding = "cyan:";
    public static String end = "Unexpected loginserver response.";
    public static String endTime = "Please try using a different world.";
    public static String engine = "The Protect Item prayer will";
    public static String entry = f262x;
    public static String error = "Please use a different world.";
    public static String event = "Visit runescape.com and vote,";
    public static String events = "Invalid username or password.";
    public static String exception = "Connection lost";
    public static String field = "Your ignore list is full. Max of 100 for free users, and 400 for members";
    public static String fields = "Walk here";
    public static String file = "slide:";
    public static String fileName = "Loading sprites - ";
    public static String filename = "flash3:";
    public static String files = "Your account must have a displayname set";
    public static String filter = "";
    public static String first = "Unable to connect.";
    public static String flags = "";
    public static String folderName = "";
    public static String font = "World";
    public static String format = "Type";
    public static String fragment = "Connecting to update server";
    public static String from = "Error connecting to server.";
    public static String f250g = "Back";
    public static String genre = "glow2:";
    public static String group = "Drop";
    public static String f251h = "";
    public static String handler = "Forgotten your password?";
    public static String hash = "Starting game engine...";
    public static String head = "Close";
    public static String header = "slide:";
    public static String headers = "Please subscribe, or use a different world.";
    public static String height = "";
    public static String host = "Loading fonts - ";
    public static String hostname = "Checking for updates - ";
    public static String hour = " seconds.";
    public static String href = "Loaded title screen";
    public static String f252i = "";
    public static String icon = "via the website, or the main game.";
    public static String id = "";
    public static String image = "green:";
    public static String images = "email address to login. Otherwise please login with your username.";
    public static String in = "PIN: ";
    public static String index = f263y;
    public static String info = "You can't add yourself to your own friend list";
    public static String input = "Please enter your password.";
    public static String item = "scroll:";
    public static String items = "setting your date of birth.";
    public static String iv = "Location";
    public static String key = "The server is being updated.";
    public static String label = "flash1:";
    public static String language = "";
    public static String last = "Bad session id.";
    public static String lat = "";
    public static String left = "Warning!";
    public static String len = "";
    public static String length = "Choose Option";
    public static String level = "";
    public static String limit = "flash1:";
    public static String line = "Press 'change your password' on front page.";
    public static String link = "white:";
    public static String list = "Please use a different world.";
    public static String locale = "Recover";
    public static String location = "Too many login attempts.";
    public static String lock = "Your attempt to log into your account was";
    public static String log = "Examine";
    public static String logger = "If you created your account after November";
    public static String login = "Loading config - ";
    public static String lon = "Service unavailable.";
    public static String f253m = "Welcome to RuneScape";
    public static String main = "Please try again later.";
    public static String map = "Please check your message-centre for details.";
    public static String max = "Please enter your username.";
    public static String media = "Loaded fonts";
    public static String message = "This world is full.";
    public static String method = "Please wait 1 minute and try again.";
    public static String min = "For more information, please take a look at";
    public static String minute = "";
    public static String mode = "Please try using a different world.";
    public static String model = "and the Protect Item prayer won't work.";
    public static String month = "You have only just left another world.";
    public static String msg = "Please try again.";
    public static String f254n = "Connecting to server...";
    public static String name = "scroll:";
    public static String names = "Hidden";
    public static String next = "Attack";
    public static String note = "RuneScape has been updated!";
    public static String off = "OFF";
    public static String offset = "white:";
    public static String options = "email address. Otherwise please use your username.";
    public static String order = "Please try using a different world.";
    public static String orientation = "To play on this world move to a free area first";
    public static String out = "Loading - please wait.";
    public static String output = "level-";
    public static String owner = "flash3:";
    public static String f255p = "Authenticator";
    public static String packageName = "for 30 days: ";
    public static String page = "";
    public static String paint = "M";
    public static String parent = "";
    public static String parser = "Ok";
    public static String pass = "Please enter a 6-digit PIN.";
    public static String password = "RuneScape is loading - please wait...";
    public static String path = "You need a members account to login to this world.";
    public static String pattern = "Members only world";
    public static String points = "shake:";
    public static String port = "Please try again later.";
    public static String pos = " has logged out.";
    public static String position = "Please wait - attempting to reestablish";
    public static String preferences = "Username/email: ";
    public static String prefix = "our privacy policy.";
    public static String prefs = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
    public static String priority = "";
    public static String progress = "Unexpected server response";
    public static String properties = "wave2:";
    public static String property = "wave:";
    public static String protocol = "Loaded update list";
    public static String provider = "to connect to is offline at the moment.";
    public static String proxy = "wave:";
    public static String proxyHost = "Privacy Policy";
    public static String f256q = "Remember username";
    public static String query = "Prepared visibility map";
    public static String queue = "Sorry invited players only.";
    public static String f257r = "Cancel";
    public static String random = "";
    public static String rating = "glow3:";
    public static String read = "FULL";
    public static String receiver = "Error connecting to server.";
    public static String ref = "You can't add yourself to your own ignore list";
    public static String repository = "Please enter your username/email address.";
    public static String request = "";
    public static String res = "Press 'recover a locked account' on front page.";
    public static String resource = "";
    public static String response = "authenticator app.";
    public static String result = "";
    public static String results = "No reply from loginserver.";
    public static String right = "almost everywhere.";
    public static String role = "";
    public static String root = "purple:";
    public static String f258s = "";
    public static String salt = "Players";
    public static String scale = "";
    public static String scheme = "";
    public static String scope = "";
    public static String score = "Trust this computer";
    public static String second = "Account locked as we suspect it has been stolen.";
    public static String secret = "log you in to this part of the website.";
    public static String selected = "Could not complete login.";
    public static String selection = "Invalid loginserver requested.";
    public static String series = "Too many connections from your address.";
    public static String server = "";
    public static String service = "Your account has not logged out from its last";
    public static String session = "created after 24th November 2010, please use your";
    public static String set = "You must enter a valid login to proceed. For accounts";
    public static String settings = "K";
    public static String share = "";
    public static String signature = "Loaded wordpack";
    public static String size = " ";
    public static String source = "Please try using a different world.";
    public static String start = "Sorry, there was an error trying to";
    public static String startTime = "unsuccessful.  Don't worry, you can sort";
    public static String state = "";
    public static String status = "";
    public static String step = "New User";
    public static String stop = "Please try again in a few minutes.";
    public static String style = "flash2:";
    public static String subject = " from your friend list first";
    public static String subtitle = "in order to play the game.  Please set it";
    public static String summary = "and then come back here!";
    public static String symbol = "Connection timed out.";
    public static String f259t = "<u=ff>Can't Log In?</u>";
    public static String table = " more options";
    public static String tag = "Unable to find ";
    public static String tags = "";
    public static String target = "";
    public static String task = "Loaded interfaces";
    public static String template = "purple:";
    public static String text = "flash2:";
    public static String this$0 = "null";
    public static String time = "The code you entered was incorrect.";
    public static String timeStamp = "Loading title screen - ";
    public static String timeout = "Set Date of Birth";
    public static String timer = "Loading interfaces - ";
    public static String timestamp = "";
    public static String title = "cyan:";
    public static String to = "shake:";
    public static String token = "Free world";
    public static String top = "This is a <col=ff0000>PvP<col=ffffff> world.";
    public static String track = "glow2:";
    public static String type = "";
    public static String f260u = "Password: ";
    public static String uid = "Login limit exceeded.";
    public static String uri = "Please try again in a few minutes.";
    public static String url = "";
    public static String user = "";
    public static String userAgent = "Prepared sound engine";
    public static String userId = "Loaded textures";
    public static String username = "";
    public static String uuid = "";
    public static String value = "Take";
    public static String values = "Your date of birth isn't set.";
    public static String verifier = "World";
    public static String version = "yellow:";
    public static String versionCode = "Loading textures - ";
    public static String versionName = "Your friend list is full. Max of 200 for free users, and 400 for members";
    public static String view = f252i;
    public static String volume = "Please try using a different world.";
    public static String f261w = "Login: ";
    public static String width = "This computers address has been blocked";
    public static String f262x = "Page has opened in a new window.";
    public static String f263y = "(Please check your popup blocker.)";
    public static String year = " is already on your ignore list";
    public static String zoom = "Players can attack each other";

    R$id() throws Throwable {
        try {
            throw new Error();
        } catch (RuntimeException $r2) {
            throw StringBuilder.append($r2, "jv.<init>(" + ')');
        }
    }

    public static int encode(CharSequence charSequence, int i, int $i1, byte[] bArr, int i2, int i3) {
        $i1 -= i;
        for (i3 = 0; i3 < $i1; i3++) {
            char $c5 = charSequence.charAt(i + i3);
            if (($c5 > '\u0000' && $c5 < '') || ($c5 >= ' ' && $c5 <= 'ÿ')) {
                bArr[i3 + i2] = (byte) $c5;
            } else if ('€' == $c5) {
                bArr[i2 + i3] = Byte.MIN_VALUE;
            } else if ('‚' == $c5) {
                bArr[i3 + i2] = (byte) -126;
            } else if ($c5 == 'ƒ') {
                bArr[i2 + i3] = (byte) -125;
            } else if ('„' == $c5) {
                bArr[i2 + i3] = (byte) -124;
            } else if ($c5 == '…') {
                bArr[i2 + i3] = (byte) -123;
            } else if ($c5 == '†') {
                bArr[i3 + i2] = (byte) -122;
            } else if ($c5 == '‡') {
                bArr[i2 + i3] = (byte) -121;
            } else if ('ˆ' == $c5) {
                bArr[i3 + i2] = (byte) -120;
            } else if ('‰' == $c5) {
                bArr[i3 + i2] = (byte) -119;
            } else if ('Š' == $c5) {
                bArr[i3 + i2] = (byte) -118;
            } else if ('‹' == $c5) {
                bArr[i2 + i3] = (byte) -117;
            } else if ($c5 == 'Œ') {
                bArr[i2 + i3] = (byte) -116;
            } else if ($c5 == 'Ž') {
                bArr[i3 + i2] = (byte) -114;
            } else if ($c5 == '‘') {
                bArr[i3 + i2] = (byte) -111;
            } else if ('’' == $c5) {
                bArr[i2 + i3] = (byte) -110;
            } else if ('“' == $c5) {
                bArr[i3 + i2] = (byte) -109;
            } else if ($c5 == '”') {
                bArr[i3 + i2] = (byte) -108;
            } else if ($c5 == '•') {
                bArr[i3 + i2] = (byte) -107;
            } else if ($c5 == '–') {
                bArr[i3 + i2] = (byte) -106;
            } else if ('—' == $c5) {
                bArr[i2 + i3] = (byte) -105;
            } else if ('˜' == $c5) {
                try {
                    bArr[i3 + i2] = (byte) -104;
                } catch (RuntimeException $r2) {
                    throw StringBuilder.append($r2, "jv.an(" + ')');
                }
            } else if ('™' == $c5) {
                bArr[i2 + i3] = (byte) -103;
            } else if ($c5 == 'š') {
                bArr[i2 + i3] = (byte) -102;
            } else if ($c5 == '›') {
                bArr[i3 + i2] = (byte) -101;
            } else if ('œ' == $c5) {
                bArr[i3 + i2] = (byte) -100;
            } else if ('ž' == $c5) {
                bArr[i3 + i2] = (byte) -98;
            } else if ($c5 == 'Ÿ') {
                bArr[i2 + i3] = (byte) -97;
            } else {
                bArr[i2 + i3] = (byte) 63;
            }
        }
        return $i1;
    }

    public static void init(int i, int i2, byte b) {
        try {
            Config $r3 = Logger.add(R$string.photo, client.this$0.key, (byte) 59);
            $r3.this$0.start(i, 1242192116);
            $r3.this$0.toString(i2, -1762468316);
            client.this$0.add($r3, (short) 255);
        } catch (RuntimeException $r5) {
            throw StringBuilder.append($r5, "jv.ec(" + ')');
        }
    }
}
