package p000;

/* compiled from: nr */
public class R$string implements FieldElement {
    public static final R$string $assertionsDisabled = new R$string(5, -1);
    public static final R$string NONE = new R$string(25, 0);
    public static final R$string TAG = new R$string(94, 2);
    public static final R$string adapter = new R$string(97, -1);
    public static final R$string address = new R$string(39, -2);
    public static final R$string all = new R$string(60, 8);
    public static final R$string body = new R$string(58, -1);
    public static final R$string buf = new R$string(83, 2);
    public static final R$string buffer = new R$string(67, 8);
    public static final R$string cache = new R$string(55, -2);
    public static final R$string channel = new R$string(48, 0);
    public static final R$string code = new R$string(8, 5);
    public static final R$string color = new R$string(0, 7);
    public static final R$string content = new R$string(21, 7);
    public static final R$string context = new R$string(93, -1);
    public static final R$string count = new R$string(43, -1);
    public static final R$string counter = new R$string(35, 6);
    public static final R$string current = new R$string(61, 3);
    public static final R$string data = new R$string(12, 8);
    public static final R$string debug = new R$string(68, 16);
    public static final R$string description = new R$string(40, 7);
    public static final R$string dir = new R$string(72, 8);
    public static final R$string directory = new R$string(30, 7);
    public static final R$string encoding = new R$string(85, -1);
    public static final R$string file = new R$string(52, 8);
    public static final R$string filename = new R$string(74, 7);
    public static final R$string filter = new R$string(80, 8);
    public static final R$string flags = new R$string(88, 1);
    public static final R$string f264g = new R$string(17, 7);
    public static final R$string group = new R$string(65, 11);
    public static final R$string handler = new R$string(51, 8);
    public static final R$string hash = new R$string(87, 0);
    public static final R$string head = new R$string(28, -1);
    public static final R$string header = new R$string(59, 8);
    public static final R$string helper = new R$string(53, 8);
    public static final R$string host = new R$string(36, 8);
    public static final R$string icon = new R$string(20, 8);
    public static final R$string id = new R$string(56, -1);
    public static final R$string image = new R$string(3, 9);
    public static final R$string images = new R$string(71, 8);
    public static final R$string info = new R$string(31, 3);
    public static final R$string items = new R$string(23, 11);
    public static final R$string key = new R$string(10, -1);
    public static final R$string label = new R$string(57, 2);
    public static final R$string left = new R$string(14, 8);
    public static final R$string length = new R$string(9, 10);
    public static final R$string level = new R$string(82, 9);
    public static final R$string line = new R$string(90, -1);
    public static final R$string link = new R$string(44, 15);
    public static final R$string lock = new R$string(34, 3);
    public static final R$string log = new R$string(6, 3);
    public static final R$string logger = new R$string(22, 3);
    public static final R$string f265m = new R$string(18, 8);
    public static final R$string map = new R$string(63, 8);
    public static final R$string max = new R$string(62, 8);
    public static final R$string message = new R$string(7, 4);
    public static final R$string min = new R$string(96, 13);
    public static final R$string name = new R$string(73, 4);
    public static final R$string next = new R$string(78, -1);
    public static final R$string offset = new R$string(49, -1);
    public static final R$string other = new R$string(79, -1);
    public static final R$string f266p = new R$string(13, 8);
    public static final R$string parent = new R$string(75, 3);
    public static final R$string password = new R$string(38, 0);
    public static final R$string path = new R$string(2, 3);
    public static final R$string photo = new R$string(26, 6);
    public static final R$string points = new R$string(1, 3);
    public static final R$string port = new R$string(64, 13);
    public static final R$string preferences = new R$string(4, 4);
    public static final R$string previous = new R$string(27, 7);
    public static final R$string f267q = new R$string(16, 8);
    public static final R$string queue = new R$string(89, 13);
    public static final R$string f268r = new R$string(84, 15);
    public static final R$string reader = new R$string(42, 2);
    public static final R$string result = new R$string(95, -1);
    public static final R$string right = new R$string(76, 9);
    public static final R$string root = new R$string(81, 3);
    public static final R$string server = new R$string(54, 3);
    public static final R$string session = new R$string(33, 7);
    public static final R$string settings = new R$string(32, 7);
    public static final R$string size = new R$string(41, 0);
    public static final R$string start = new R$string(91, 16);
    public static final R$string f269t = new R$string(19, 8);
    public static final R$string tag = new R$string(46, 14);
    public static final R$string text = new R$string(47, -1);
    public static final R$string this$0 = new R$string(45, -1);
    public static final R$string title = new R$string(29, 8);
    public static final R$string to = new R$string(92, -1);
    public static final R$string type = new R$string(66, 4);
    public static final R$string uri = new R$string(86, 9);
    public static final R$string url = new R$string(69, 16);
    public static final R$string user = new R$string(37, 7);
    public static final R$string value = new R$string(11, 3);
    public static final R$string values = new R$string(24, 3);
    public static final R$string version = new R$string(15, 3);
    public static final R$string view = new R$string(50, -2);
    public static final R$string width = new R$string(70, 4);
    public static final R$string f270y = new R$string(77, 3);
    final int index;
    final int input;

    R$string(int $i0, int i) {
        try {
            this.index = 695302905 * $i0;
            this.input = -827987301 * i;
        } catch (RuntimeException $r1) {
            throw StringBuilder.append($r1, "nr.<init>(" + ')');
        }
    }
}
